mysql:
    host: pacemp.ctl3vgambyug.us-west-2.rds.amazonaws.com
    user: admin
    password: pace_marketplace
    db: pace_mp

smtp:
    server: smtp.gmail.com
    port: 465
    username: jammr.marketplace@gmail.com
    password: jammr@pacemp
    default_sender: jammr.marketplace@gmail.com
    ssl: True
    tls: True